### ISSUE TITLE
NotImplementedError when saving Calibrants

### ISSUE THREAD

**Issue by wulfbear** [Tarskin/HappyTools#48]
**Describe the bug**
Saving of calibrants after Peak Detection in Example File is not working.
Return text in py console:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\kaihi\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\kaihi\Desktop\HappyTools-master\HappyTools.py", line 388, in save_calibrants
    save_calibrants(self)
  File "C:\Users\kaihi\Desktop\HappyTools-master\HappyTools\util\functions.py", line 42, in save_calibrants
    raise NotImplementedError('This feature is not implemented in the ' +
NotImplementedError: This feature is not implemented in the refactor yet.`

**To Reproduce**
1. Go to 'File\OpenChromatogram\IgG Vtag 1_ACQUITY FLR ChA...'
2. Perform Smoothing and Baseline Correction as in Tutorial.
3. Click on 'Advanced\Peak Identification'
4. See peaks being identified.
5. Click on 'Advanced\SaveCalibrant'
4. See error in console.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15078392/63415072-6a5af980-c3fd-11e9-9434-3ecb592440de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 x bit
 - Browser Google Chrome 76.0.3809.100
 - Version HappyTools - 0.1-beta1 Build 190718a

**Comment by Tarskin** [comment]
This is my failure, this feature still needs to be re-designed as I wasn't too happy with the old implementation of it.
