### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by emroberts95** [Tarskin/HappyTools#54]
After navigating to the program location and typing "HappyTools.py" I get the following error message:

> C:\mypath\HappyTools> python HappyTools.py
Traceback (most recent call last):
  File "HappyTools.py", line 43, in <module>
    from HappyTools.util.peak_detection import PeakDetection
  File "C:\mypath\HappyTools\HappyTools\util\peak_detection.py", line 3, in <module>
    from HappyTools.bin.peak import Peak
  File "C:\mypath\HappyTools\HappyTools\bin\peak.py", line 5, in <module>
    from scipy.interpolate import InterpolatedUnivariateSpline
  File "C:\mypath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from .interpolate import *
  File "C:\mypath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\interpolate\interpolate.py", line 15, in <module>
    import scipy.special as spec
  File "C:\mypath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\special\__init__.py", line 634, in <module>
    from . import _ufuncs
ImportError: DLL load failed: The specified module could not be found.

**Comment by Tarskin** [comment]
Can you specify the exact OS and versions of python and dependant libraries that you are using? I have been unable to reproduce this, to date.

**Comment by emroberts95** [comment]
Sure, I'm using Windows 10 and Python 3.7.7. How do I find out the version of dependent libraries?

**Comment by Tarskin** [comment]
The easiest way would be to do a pip freeze as this will list all installed packages and their versions.

Are you able to run any Python program at all? The reason that I ask this is that the error seems related to your OS rather than to HappyTools...

**Comment by emroberts95** [comment]
Here are the versions of the dependent packages:
certifi==2019.11.28
chardet==3.0.4
chart-studio==1.0.0
cycler==0.10.0
idna==2.8
kiwisolver==1.1.0
matplotlib==3.1.3
numpy==1.18.1
pandas==1.0.0
PeakUtils==1.3.3
plotly==4.5.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
retrying==1.3.3
scipy==1.4.1
six==1.14.0
urllib3==1.25.8

But yes, today while trying to run a completely different program I got the same error. I will troubleshoot this on my own and post updates here.

**Comment by emroberts95** [comment]
It's working now. I had to do a clean install of Windows 10 and then update it, details here: [(https://www.reddit.com/r/techsupport/comments/fpy47t/dll_errors_on_somewhat_new_dell_xps_15_laptop/)]
